//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PForm.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [JsonIgnore]
        public int ID { get; set; }
        [JsonIgnore]
        public string CommentID { get; set; }
        public string Comment1 { get; set; }
        [JsonIgnore]
        public int Sort { get; set; }
    }
}
